# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(default=datetime.datetime(2018, 3, 5, 5, 55, 34, 778388, tzinfo=utc))),
                ('address', models.TextField(max_length=200)),
                ('join_date', models.DateTimeField(default=datetime.datetime(2018, 3, 5, 5, 55, 34, 778458, tzinfo=utc))),
                ('emai', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.BooleanField()),
                ('leave_left', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
