# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='updation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
