# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180305_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
