# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_leave_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emai',
            new_name='email',
        ),
    ]
