# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20180305_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic', models.FloatField()),
                ('HRA', models.FloatField()),
            ],
        ),
    ]
