# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20180306_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='first_name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
