# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 09:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_salary_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_earnings',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='income_tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='loss_of_pay',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='public_holidays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='weekly_off',
            field=models.IntegerField(default=0),
        ),
    ]
