# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20180306_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('leave_type', models.CharField(choices=[('seek', 'SeekLeave'), ('casual', 'CausualLeave')], max_length=2)),
                ('work_from_home', models.BooleanField()),
                ('prev_leave_left', models.IntegerField(default=0)),
                ('casual_leave_left', models.IntegerField(default=0)),
                ('first_name', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
