# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20180306_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(choices=[('seek', 'SeekLeave'), ('casual', 'CausualLeave')], max_length=6, null=True),
        ),
    ]
