# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20180306_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark',
            field=models.CharField(choices=[('P', 'Present'), ('a', 'absent'), ('h', 'halfday')], default=False, max_length=7),
        ),
    ]
