# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_remove_holiday_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='first_name',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
