# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20180313_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
