# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 06:35
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic', models.FloatField(default='0.0')),
                ('hra', models.FloatField(default='0.0')),
                ('conveyance_allow', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('special_allowence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('loss_of_pay', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('gross_deduction', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('total_days', models.IntegerField(default=0)),
                ('weekly_off', models.IntegerField(default=0)),
                ('public_holidays', models.IntegerField(default=0)),
                ('paid_days', models.IntegerField(default=0)),
                ('net_salary', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
