# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.TextField(blank=True, max_length=100, null=True)),
                ('address_line2', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('fax', models.TextField(max_length=50)),
                ('website', models.EmailField(max_length=255)),
            ],
        ),
    ]
