# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 06:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('basic', models.FloatField(default='0.0')),
                ('hra', models.FloatField(default='0.0')),
                ('conveyance_allow', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
            ],
        ),
    ]
