# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_department_designation_holiday_jobtype_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
