# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mark', models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT'), ('W', 'WORK FROM HOME'), ('H', 'HALF DAY')], default='P', max_length=15)),
                ('leave_type', models.CharField(blank=True, choices=[('C', 'CASUAL LEAVE'), ('P', 'PRIVILEGE LEAVE'), ('S', 'SEEK LEAVE')], max_length=16, null=True)),
                ('rem_privilege_leave', models.IntegerField(blank=True, null=True)),
                ('rem_casual_leave', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
