# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180529_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[('1', 'PRESENT'), ('0', 'ABSENT'), ('0.5', 'HALF DAY')], default='1'),
        ),
    ]
