# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180529_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[(1, 'PRESENT'), (0, 'ABSENT'), (0.5, 'HALF DAY')], default=1),
        ),
    ]
