# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180531_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.FloatField(choices=[(1, 'PRESENT'), (0, 'ABSENT'), (0.5, 'HALF DAY')], default=1),
        ),
    ]
